export const translations = {
  id: {
    pageTitle: 'RISEFARM - Pelopor Agritech Ubi Nusantara',
    nav: { about: 'Tentang Kami', products: 'Produk', process: 'Proses', gallery: 'Galeri', articles: 'Artikel', contact: 'Kontak', detail: 'Pelajari Detail', contactBtn: 'Hubungi Kami', write: 'Tulis Artikel' },
    hero: { badge: 'Penyedia ubi berkualitas', title: 'Pasokan Ubi yang Stabil, Terukur, dan Siap untuk Skala Bisnis.', desc: 'Dari bibit unggul hingga ke tangan Anda. RISEFARM menghadirkan inovasi pertanian ubi yang berkelanjutan, memberdayakan petani lokal, dan menghasilkan panen kualitas premium untuk kebutuhan supermarket & ekspor.', cta1: 'Lihat Produk Kami', ctaArticles: 'Baca Artikel & Berita' },
    about: { badge: 'Alami & Berkelanjutan', kicker: 'Tentang RISEFARM', title: 'Akar Kuat untuk <br/>Pertanian Modern', desc1: 'RISEFARM bukan sekadar lahan pertanian. Kami adalah ekosistem agritech yang berdedikasi untuk merevolusi budidaya ubi di Nusantara. Berdiri dengan visi untuk menciptakan ketahanan pangan yang berkelanjutan dan menyejahterakan petani lokal.', desc2: 'Kami memadukan kearifan lokal dengan teknologi presisi—mulai dari seleksi bibit, pemantauan tanah, hingga distribusi cerdas, memastikan setiap ubi yang sampai ke tangan Anda memiliki kualitas nutrisi dan rasa terbaik.', land: 'Hektar Lahan Aktif', farmers: 'Mitra Petani' },
    why: { title: 'Mengapa Memilih RISEFARM?', desc: 'Komitmen kami pada kualitas, lingkungan, dan komunitas membedakan kami di setiap langkah rantai pasok.', q1: 'Kualitas Premium', q1d: 'Sistem kontrol kualitas ketat memastikan ubi segar, manis, dan kaya nutrisi.', q2: 'Ramah Lingkungan', q2d: 'Metode pertanian regeneratif yang menjaga kesuburan tanah untuk generasi mendatang.', q3: 'Agritech Modern', q3d: 'Pupuk racikan berbasis kebutuhan tanah, dan bibit unggul hasil kultur jaringan untuk menciptakan sistem pertanian yang lebih efisien, produktif, dan menghasilkan panen berkualitas tinggi secara konsisten.', q4: 'Pemberdayaan Lokal', q4d: 'Bermitra dengan puluhan petani desa, memberikan pelatihan dan pembagian hasil yang adil.' },
    products: { kicker: 'Hasil Bumi Terbaik', title: 'Produk & Layanan Kami', desc: 'Dari ubi madu yang manis legit hingga varietas ungu yang kaya antioksidan, kami menyediakan yang terbaik untuk Anda.', badge1: 'Unggulan', badge3: 'Baru', p1: 'Ubi Segar Kualitas Ekspor', p1d: 'Pilihan ubi premium lengkap seperti Cilembu, ungu, Jepang, Murasaki, Pinky, TW, dan lainnya. Seluruh produk melalui proses sortir ketat dengan kualitas terjamin serta bebas dari pestisida kimia berbahaya, sehingga lebih sehat dan siap bersaing di pasar modern.', p2: 'Ubi Segar Kualitas Supermarket', p2d: 'Kami menyediakan ubi segar berkualitas tinggi yang siap untuk distribusi ke supermarket dan toko ritel.', p3: 'Sayuran dan buah buahan', p3d: 'Sayuran dan buah buahan segar yang tumbuh dengan metode pertanian organik kami menyediakan kualitas ekspor dan kualitas supermarket (melon, jeruk, wortel, bayam dll).', detail: 'Pelajari Detail' },
    process: { kicker: 'Perjalanan Kualitas', title: 'Dari Kebun Ke Meja Anda', desc: 'Setiap tahap dipantau secara presisi untuk menjamin kualitas terbaik.', s1: '1. Pembibitan', s1d: 'Seleksi varietas unggul di fasilitas nursery khusus kami.', s2: '2. Penanaman', s2d: 'Perawatan intensif dengan pemupukan organik dan irigasi presisi.', s3: '3. Panen & Sortir', s3d: 'Dipanen pada usia optimal, disortir ketat berdasarkan standar mutu.', s4: '4. Distribusi', s4d: 'Pengemasan aman dan logistik cepat agar kesegaran tetap terjaga.' },
    gallery: { kicker: 'Dokumentasi', title: 'Melihat Lebih Dekat RISEFARM', all: 'Lihat Semua', caption1: 'Pemberdayaan Petani Lokal' },
    articles: { kicker: 'Update RISEFARM', title: 'Artikel & Berita Terbaru', desc: 'Bagikan cerita panen, inovasi pertanian, aktivitas kebun, dan kabar terbaru perusahaan dalam satu halaman yang rapi.', viewAll: 'Lihat Semua Artikel', write: 'Tulis Sekarang' },
    testimonials: { title: 'Suara Mitra Kami', t1: '"Sejak bermitra dengan RISEFARM, hasil panen lahan saya meningkat secara signifikan. Edukasi pertanian organik yang diberikan sangat mengubah pola pikir kami sebagai petani di desa."', t1n: 'Bapak Sugeng', t1r: 'Ketua Kelompok Tani, Jawa Barat', t2: '"Kualitas pasokan ubi madu dari RISEFARM selalu konsisten. Hal ini sangat penting bagi industri pengolahan makanan kami. Pengiriman selalu tepat waktu dan ukurannya presisi."', t2n: 'Ibu Diana', t2r: 'Direktur Pengadaan, PT Nutrisi Maju' },
    cta: { title: 'Mari Tumbuh Bersama <span class="text-orange-400">RISEFARM</span>', desc: 'Apakah Anda petani yang ingin berkembang, atau perusahaan yang membutuhkan pasokan ubi premium berkelanjutan? Kami siap menjadi mitra terbaik Anda.', btn1: 'Jadilah Mitra Kami', btn2: 'Pesan Produk' },
    footer: { desc: 'Menghadirkan inovasi agritech dalam budidaya ubi untuk masa depan pangan nusantara yang lebih baik, alami, dan berkelanjutan.', nav: 'Navigasi', contact: 'Hubungi Kami', copyright: 'RISEFARM Indonesia. Hak Cipta Dilindungi.', tagline: 'Menumbuhkan Potensi Ubi, Mengangkat Masa Depan Pertanian.' },
    news: { title: 'Artikel & Berita RISEFARM', back: 'Kembali ke daftar artikel', disclaimer: 'Artikel ini hanya tersedia dalam Bahasa Indonesia.', team: 'Tim Agritech RISEFARM', readMore: 'Baca selengkapnya', defaultCategory: 'Artikel' }
  },
  en: {
    pageTitle: 'RISEFARM - Pioneer of Indonesian Sweet Potato Agritech',
    nav: { about: 'About Us', products: 'Products', process: 'Process', gallery: 'Gallery', articles: 'Articles', contact: 'Contact', detail: 'Learn More', contactBtn: 'Contact Us', write: 'Write Article' },
    hero: { badge: 'Quality sweet potato supplier', title: 'Stable, Measurable Sweet Potato Supply Ready for Business Scale.', desc: 'From superior seedlings to your hands. RISEFARM delivers sustainable sweet potato farming innovation, empowers local farmers, and produces premium harvests for supermarkets and export markets.', cta1: 'View Our Products', ctaArticles: 'Read Articles & News' },
    about: { badge: 'Natural & Sustainable', kicker: 'About RISEFARM', title: 'Strong Roots for <br/>Modern Agriculture', desc1: 'RISEFARM is more than farmland. We are an agritech ecosystem dedicated to transforming sweet potato cultivation across Indonesia, with a vision to build sustainable food security and improve local farmers’ livelihoods.', desc2: 'We combine local wisdom with precision technology—from seed selection and soil monitoring to smart distribution—ensuring every sweet potato delivered to you has the best taste and nutritional quality.', land: 'Hectares of Active Farmland', farmers: 'Farmer Partners' },
    why: { title: 'Why Choose RISEFARM?', desc: 'Our commitment to quality, sustainability, and community sets us apart at every step of the supply chain.', q1: 'Premium Quality', q1d: 'Strict quality control ensures fresh, sweet, and nutrient-rich sweet potatoes.', q2: 'Eco-Friendly', q2d: 'Regenerative farming methods preserve soil fertility for future generations.', q3: 'Modern Agritech', q3d: 'Custom soil-based fertilizers and tissue-culture superior seedlings create a more efficient, productive farming system with consistently high-quality yields.', q4: 'Local Empowerment', q4d: 'Partnering with dozens of village farmers through training and fair profit sharing.' },
    products: { kicker: 'Best Harvest', title: 'Our Products & Services', desc: 'From honey sweet potatoes to antioxidant-rich purple varieties, we provide the best for you.', badge1: 'Featured', badge3: 'New', p1: 'Export-Grade Fresh Sweet Potatoes', p1d: 'A complete range of premium sweet potatoes such as Cilembu, purple, Japanese, Murasaki, Pinky, TW, and more. All products go through strict sorting with guaranteed quality and are free from harmful chemical pesticides, making them healthier and ready for modern markets.', p2: 'Supermarket-Grade Fresh Sweet Potatoes', p2d: 'We provide high-quality fresh sweet potatoes ready for distribution to supermarkets and retail stores.', p3: 'Vegetables and Fruits', p3d: 'Fresh vegetables and fruits grown with our organic farming methods. We supply both export-grade and supermarket-grade produce such as melons, oranges, carrots, spinach, and more.', detail: 'Learn More' },
    process: { kicker: 'Quality Journey', title: 'From Farm to Your Table', desc: 'Every stage is monitored with precision to ensure top quality.', s1: '1. Seedling', s1d: 'Selection of superior varieties in our dedicated nursery facilities.', s2: '2. Planting', s2d: 'Intensive care with organic fertilization and precision irrigation.', s3: '3. Harvest & Sorting', s3d: 'Harvested at optimal maturity and strictly sorted based on quality standards.', s4: '4. Distribution', s4d: 'Safe packaging and fast logistics to preserve freshness.' },
    gallery: { kicker: 'Documentation', title: 'A Closer Look at RISEFARM', all: 'View All', caption1: 'Empowering Local Farmers' },
    articles: { kicker: 'RISEFARM Updates', title: 'Latest Articles & News', desc: 'Share harvest stories, farming innovation, field activities, and company updates in one clean page.', viewAll: 'View All Articles', write: 'Write Now' },
    testimonials: { title: 'What Our Partners Say', t1: '"Since partnering with RISEFARM, the yield from my land has increased significantly. The organic farming education they provided has truly changed our mindset as village farmers."', t1n: 'Mr. Sugeng', t1r: 'Farmer Group Leader, West Java', t2: '"The quality of honey sweet potato supply from RISEFARM is always consistent. This is crucial for our food processing industry. Delivery is always on time and sizing is precise."', t2n: 'Mrs. Diana', t2r: 'Procurement Director, PT Nutrisi Maju' },
    cta: { title: 'Let’s Grow Together with <span class="text-orange-400">RISEFARM</span>', desc: 'Are you a farmer looking to grow, or a company needing sustainable premium sweet potato supply? We are ready to be your best partner.', btn1: 'Become Our Partner', btn2: 'Order Products' },
    footer: { desc: 'Bringing agritech innovation to sweet potato cultivation for a better, more natural, and sustainable future of Indonesian food.', nav: 'Navigation', contact: 'Contact Us', copyright: 'RISEFARM Indonesia. All Rights Reserved.', tagline: 'Growing Sweet Potato Potential, Elevating the Future of Agriculture.' },
    news: { title: 'RISEFARM Articles & News', back: 'Back to articles list', disclaimer: 'This article is only available in Bahasa Indonesia.', team: 'RISEFARM Agritech Team', readMore: 'Read more', defaultCategory: 'Article' }
  }
};
